<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto

namespace Protos;

/**
 * Protobuf enum <code>protos.SchemaUpdate.Directive</code>
 */
class SchemaUpdate_Directive
{
    /**
     * <code>NONE = 0;</code>
     */
    const NONE = 0;
    /**
     * <code>INDEX = 1;</code>
     */
    const INDEX = 1;
    /**
     * <code>REVERSE = 2;</code>
     */
    const REVERSE = 2;
}

