<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>protos.SchemaUpdate</code>
 */
class SchemaUpdate extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string predicate = 1;</code>
     */
    private $predicate = '';
    /**
     * <code>uint32 value_type = 2;</code>
     */
    private $value_type = 0;
    /**
     * <code>.protos.SchemaUpdate.Directive directive = 3;</code>
     */
    private $directive = 0;
    /**
     * <code>repeated string tokenizer = 4;</code>
     */
    private $tokenizer;

    public function __construct() {
        \GPBMetadata\Schema::initOnce();
        parent::__construct();
    }

    /**
     * <code>string predicate = 1;</code>
     */
    public function getPredicate()
    {
        return $this->predicate;
    }

    /**
     * <code>string predicate = 1;</code>
     */
    public function setPredicate($var)
    {
        GPBUtil::checkString($var, True);
        $this->predicate = $var;

        return $this;
    }

    /**
     * <code>uint32 value_type = 2;</code>
     */
    public function getValueType()
    {
        return $this->value_type;
    }

    /**
     * <code>uint32 value_type = 2;</code>
     */
    public function setValueType($var)
    {
        GPBUtil::checkUint32($var);
        $this->value_type = $var;

        return $this;
    }

    /**
     * <code>.protos.SchemaUpdate.Directive directive = 3;</code>
     */
    public function getDirective()
    {
        return $this->directive;
    }

    /**
     * <code>.protos.SchemaUpdate.Directive directive = 3;</code>
     */
    public function setDirective($var)
    {
        GPBUtil::checkEnum($var, \Protos\SchemaUpdate_Directive::class);
        $this->directive = $var;

        return $this;
    }

    /**
     * <code>repeated string tokenizer = 4;</code>
     */
    public function getTokenizer()
    {
        return $this->tokenizer;
    }

    /**
     * <code>repeated string tokenizer = 4;</code>
     */
    public function setTokenizer(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->tokenizer = $arr;

        return $this;
    }

}

