<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>protos.SchemaRequest</code>
 */
class SchemaRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>uint32 group_id = 1;</code>
     */
    private $group_id = 0;
    /**
     * <code>repeated string predicates = 2;</code>
     */
    private $predicates;
    /**
     * <pre>
     * fields can be on of type, index, reverse or tokenizer
     * </pre>
     *
     * <code>repeated string fields = 3;</code>
     */
    private $fields;

    public function __construct() {
        \GPBMetadata\Schema::initOnce();
        parent::__construct();
    }

    /**
     * <code>uint32 group_id = 1;</code>
     */
    public function getGroupId()
    {
        return $this->group_id;
    }

    /**
     * <code>uint32 group_id = 1;</code>
     */
    public function setGroupId($var)
    {
        GPBUtil::checkUint32($var);
        $this->group_id = $var;

        return $this;
    }

    /**
     * <code>repeated string predicates = 2;</code>
     */
    public function getPredicates()
    {
        return $this->predicates;
    }

    /**
     * <code>repeated string predicates = 2;</code>
     */
    public function setPredicates(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->predicates = $arr;

        return $this;
    }

    /**
     * <pre>
     * fields can be on of type, index, reverse or tokenizer
     * </pre>
     *
     * <code>repeated string fields = 3;</code>
     */
    public function getFields()
    {
        return $this->fields;
    }

    /**
     * <pre>
     * fields can be on of type, index, reverse or tokenizer
     * </pre>
     *
     * <code>repeated string fields = 3;</code>
     */
    public function setFields(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->fields = $arr;

        return $this;
    }

}

