<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graphresponse.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>protos.Latency</code>
 */
class Latency extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string parsing = 1;</code>
     */
    private $parsing = '';
    /**
     * <code>string processing = 2;</code>
     */
    private $processing = '';
    /**
     * <code>string pb = 3;</code>
     */
    private $pb = '';

    public function __construct() {
        \GPBMetadata\Graphresponse::initOnce();
        parent::__construct();
    }

    /**
     * <code>string parsing = 1;</code>
     */
    public function getParsing()
    {
        return $this->parsing;
    }

    /**
     * <code>string parsing = 1;</code>
     */
    public function setParsing($var)
    {
        GPBUtil::checkString($var, True);
        $this->parsing = $var;

        return $this;
    }

    /**
     * <code>string processing = 2;</code>
     */
    public function getProcessing()
    {
        return $this->processing;
    }

    /**
     * <code>string processing = 2;</code>
     */
    public function setProcessing($var)
    {
        GPBUtil::checkString($var, True);
        $this->processing = $var;

        return $this;
    }

    /**
     * <code>string pb = 3;</code>
     */
    public function getPb()
    {
        return $this->pb;
    }

    /**
     * <code>string pb = 3;</code>
     */
    public function setPb($var)
    {
        GPBUtil::checkString($var, True);
        $this->pb = $var;

        return $this;
    }

}

