<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graphresponse.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>protos.Node</code>
 */
class Node extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string attribute = 1;</code>
     */
    private $attribute = '';
    /**
     * <code>repeated .protos.Property properties = 2;</code>
     */
    private $properties;
    /**
     * <pre>
     * Each node can have multiple children
     * </pre>
     *
     * <code>repeated .protos.Node children = 3;</code>
     */
    private $children;

    public function __construct() {
        \GPBMetadata\Graphresponse::initOnce();
        parent::__construct();
    }

    /**
     * <code>string attribute = 1;</code>
     */
    public function getAttribute()
    {
        return $this->attribute;
    }

    /**
     * <code>string attribute = 1;</code>
     */
    public function setAttribute($var)
    {
        GPBUtil::checkString($var, True);
        $this->attribute = $var;

        return $this;
    }

    /**
     * <code>repeated .protos.Property properties = 2;</code>
     */
    public function getProperties()
    {
        return $this->properties;
    }

    /**
     * <code>repeated .protos.Property properties = 2;</code>
     */
    public function setProperties(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protos\Property::class);
        $this->properties = $arr;

        return $this;
    }

    /**
     * <pre>
     * Each node can have multiple children
     * </pre>
     *
     * <code>repeated .protos.Node children = 3;</code>
     */
    public function getChildren()
    {
        return $this->children;
    }

    /**
     * <pre>
     * Each node can have multiple children
     * </pre>
     *
     * <code>repeated .protos.Node children = 3;</code>
     */
    public function setChildren(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protos\Node::class);
        $this->children = $arr;

        return $this;
    }

}

