<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graphresponse.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>protos.Num</code>
 */
class Num extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>uint64 val = 1;</code>
     */
    private $val = 0;

    public function __construct() {
        \GPBMetadata\Graphresponse::initOnce();
        parent::__construct();
    }

    /**
     * <code>uint64 val = 1;</code>
     */
    public function getVal()
    {
        return $this->val;
    }

    /**
     * <code>uint64 val = 1;</code>
     */
    public function setVal($var)
    {
        GPBUtil::checkUint64($var);
        $this->val = $var;

        return $this;
    }

}

