<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graphresponse.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>protos.Property</code>
 */
class Property extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string prop = 1;</code>
     */
    private $prop = '';
    /**
     * <code>.protos.Value value = 2;</code>
     */
    private $value = null;

    public function __construct() {
        \GPBMetadata\Graphresponse::initOnce();
        parent::__construct();
    }

    /**
     * <code>string prop = 1;</code>
     */
    public function getProp()
    {
        return $this->prop;
    }

    /**
     * <code>string prop = 1;</code>
     */
    public function setProp($var)
    {
        GPBUtil::checkString($var, True);
        $this->prop = $var;

        return $this;
    }

    /**
     * <code>.protos.Value value = 2;</code>
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * <code>.protos.Value value = 2;</code>
     */
    public function setValue(&$var)
    {
        GPBUtil::checkMessage($var, \Protos\Value::class);
        $this->value = $var;

        return $this;
    }

}

