<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graphresponse.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>protos.Response</code>
 */
class Response extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .protos.Node n = 1;</code>
     */
    private $n;
    /**
     * <code>.protos.Latency l = 2;</code>
     */
    private $l = null;
    /**
     * <code>map&lt;string, uint64&gt; AssignedUids = 3;</code>
     */
    private $AssignedUids;
    /**
     * <code>repeated .protos.SchemaNode schema = 4;</code>
     */
    private $schema;

    public function __construct() {
        \GPBMetadata\Graphresponse::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .protos.Node n = 1;</code>
     */
    public function getN()
    {
        return $this->n;
    }

    /**
     * <code>repeated .protos.Node n = 1;</code>
     */
    public function setN(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protos\Node::class);
        $this->n = $arr;

        return $this;
    }

    /**
     * <code>.protos.Latency l = 2;</code>
     */
    public function getL()
    {
        return $this->l;
    }

    /**
     * <code>.protos.Latency l = 2;</code>
     */
    public function setL(&$var)
    {
        GPBUtil::checkMessage($var, \Protos\Latency::class);
        $this->l = $var;

        return $this;
    }

    /**
     * <code>map&lt;string, uint64&gt; AssignedUids = 3;</code>
     */
    public function getAssignedUids()
    {
        return $this->AssignedUids;
    }

    /**
     * <code>map&lt;string, uint64&gt; AssignedUids = 3;</code>
     */
    public function setAssignedUids(&$var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->AssignedUids = $arr;

        return $this;
    }

    /**
     * <code>repeated .protos.SchemaNode schema = 4;</code>
     */
    public function getSchema()
    {
        return $this->schema;
    }

    /**
     * <code>repeated .protos.SchemaNode schema = 4;</code>
     */
    public function setSchema(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protos\SchemaNode::class);
        $this->schema = $arr;

        return $this;
    }

}

