<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>protos.Payload</code>
 */
class Payload extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>bytes Data = 1;</code>
     */
    private $Data = '';

    public function __construct() {
        \GPBMetadata\Payload::initOnce();
        parent::__construct();
    }

    /**
     * <code>bytes Data = 1;</code>
     */
    public function getData()
    {
        return $this->Data;
    }

    /**
     * <code>bytes Data = 1;</code>
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, False);
        $this->Data = $var;

        return $this;
    }

}

