<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>api.Assigned</code>
 */
class Assigned extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>map&lt;string, string&gt; uids = 1;</code>
     */
    private $uids;
    /**
     * <code>.api.TxnContext context = 2;</code>
     */
    private $context = null;

    public function __construct() {
        \GPBMetadata\Api::initOnce();
        parent::__construct();
    }

    /**
     * <code>map&lt;string, string&gt; uids = 1;</code>
     */
    public function getUids()
    {
        return $this->uids;
    }

    /**
     * <code>map&lt;string, string&gt; uids = 1;</code>
     */
    public function setUids(&$var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->uids = $arr;

        return $this;
    }

    /**
     * <code>.api.TxnContext context = 2;</code>
     */
    public function getContext()
    {
        return $this->context;
    }

    /**
     * <code>.api.TxnContext context = 2;</code>
     */
    public function setContext(&$var)
    {
        GPBUtil::checkMessage($var, \Api\TxnContext::class);
        $this->context = $var;

        return $this;
    }

}

