<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>api.AssignedIds</code>
 */
class AssignedIds extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>uint64 startId = 1;</code>
     */
    private $startId = 0;
    /**
     * <code>uint64 endId = 2;</code>
     */
    private $endId = 0;

    public function __construct() {
        \GPBMetadata\Api::initOnce();
        parent::__construct();
    }

    /**
     * <code>uint64 startId = 1;</code>
     */
    public function getStartId()
    {
        return $this->startId;
    }

    /**
     * <code>uint64 startId = 1;</code>
     */
    public function setStartId($var)
    {
        GPBUtil::checkUint64($var);
        $this->startId = $var;

        return $this;
    }

    /**
     * <code>uint64 endId = 2;</code>
     */
    public function getEndId()
    {
        return $this->endId;
    }

    /**
     * <code>uint64 endId = 2;</code>
     */
    public function setEndId($var)
    {
        GPBUtil::checkUint64($var);
        $this->endId = $var;

        return $this;
    }

}

