<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>api.Check</code>
 */
class Check extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Api::initOnce();
        parent::__construct();
    }

}

