<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>api.Facet</code>
 */
class Facet extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string key = 1;</code>
     */
    private $key = '';
    /**
     * <code>bytes value = 2;</code>
     */
    private $value = '';
    /**
     * <code>.api.Facet.ValType val_type = 3;</code>
     */
    private $val_type = 0;
    /**
     * <pre>
     * tokens of value.
     * </pre>
     *
     * <code>repeated string tokens = 4;</code>
     */
    private $tokens;
    /**
     * <pre>
     * not stored, only used for query.
     * </pre>
     *
     * <code>string alias = 5;</code>
     */
    private $alias = '';

    public function __construct() {
        \GPBMetadata\Api::initOnce();
        parent::__construct();
    }

    /**
     * <code>string key = 1;</code>
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * <code>string key = 1;</code>
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

    /**
     * <code>bytes value = 2;</code>
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * <code>bytes value = 2;</code>
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->value = $var;

        return $this;
    }

    /**
     * <code>.api.Facet.ValType val_type = 3;</code>
     */
    public function getValType()
    {
        return $this->val_type;
    }

    /**
     * <code>.api.Facet.ValType val_type = 3;</code>
     */
    public function setValType($var)
    {
        GPBUtil::checkEnum($var, \Api\Facet_ValType::class);
        $this->val_type = $var;

        return $this;
    }

    /**
     * <pre>
     * tokens of value.
     * </pre>
     *
     * <code>repeated string tokens = 4;</code>
     */
    public function getTokens()
    {
        return $this->tokens;
    }

    /**
     * <pre>
     * tokens of value.
     * </pre>
     *
     * <code>repeated string tokens = 4;</code>
     */
    public function setTokens(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->tokens = $arr;

        return $this;
    }

    /**
     * <pre>
     * not stored, only used for query.
     * </pre>
     *
     * <code>string alias = 5;</code>
     */
    public function getAlias()
    {
        return $this->alias;
    }

    /**
     * <pre>
     * not stored, only used for query.
     * </pre>
     *
     * <code>string alias = 5;</code>
     */
    public function setAlias($var)
    {
        GPBUtil::checkString($var, True);
        $this->alias = $var;

        return $this;
    }

}

