<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>api.Value</code>
 */
class Value extends \Google\Protobuf\Internal\Message
{
    protected $val;

    public function __construct() {
        \GPBMetadata\Api::initOnce();
        parent::__construct();
    }

    /**
     * <code>string default_val = 1;</code>
     */
    public function getDefaultVal()
    {
        return $this->readOneof(1);
    }

    /**
     * <code>string default_val = 1;</code>
     */
    public function setDefaultVal($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * <code>bytes bytes_val = 2;</code>
     */
    public function getBytesVal()
    {
        return $this->readOneof(2);
    }

    /**
     * <code>bytes bytes_val = 2;</code>
     */
    public function setBytesVal($var)
    {
        GPBUtil::checkString($var, False);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * <code>int64 int_val = 3;</code>
     */
    public function getIntVal()
    {
        return $this->readOneof(3);
    }

    /**
     * <code>int64 int_val = 3;</code>
     */
    public function setIntVal($var)
    {
        GPBUtil::checkInt64($var);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * <code>bool bool_val = 4;</code>
     */
    public function getBoolVal()
    {
        return $this->readOneof(4);
    }

    /**
     * <code>bool bool_val = 4;</code>
     */
    public function setBoolVal($var)
    {
        GPBUtil::checkBool($var);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * <code>string str_val = 5;</code>
     */
    public function getStrVal()
    {
        return $this->readOneof(5);
    }

    /**
     * <code>string str_val = 5;</code>
     */
    public function setStrVal($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * <code>double double_val = 6;</code>
     */
    public function getDoubleVal()
    {
        return $this->readOneof(6);
    }

    /**
     * <code>double double_val = 6;</code>
     */
    public function setDoubleVal($var)
    {
        GPBUtil::checkDouble($var);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * <pre>
     * Geo data in WKB format
     * </pre>
     *
     * <code>bytes geo_val = 7;</code>
     */
    public function getGeoVal()
    {
        return $this->readOneof(7);
    }

    /**
     * <pre>
     * Geo data in WKB format
     * </pre>
     *
     * <code>bytes geo_val = 7;</code>
     */
    public function setGeoVal($var)
    {
        GPBUtil::checkString($var, False);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * <code>bytes date_val = 8;</code>
     */
    public function getDateVal()
    {
        return $this->readOneof(8);
    }

    /**
     * <code>bytes date_val = 8;</code>
     */
    public function setDateVal($var)
    {
        GPBUtil::checkString($var, False);
        $this->writeOneof(8, $var);

        return $this;
    }

    /**
     * <code>bytes datetime_val = 9;</code>
     */
    public function getDatetimeVal()
    {
        return $this->readOneof(9);
    }

    /**
     * <code>bytes datetime_val = 9;</code>
     */
    public function setDatetimeVal($var)
    {
        GPBUtil::checkString($var, False);
        $this->writeOneof(9, $var);

        return $this;
    }

    /**
     * <code>string password_val = 10;</code>
     */
    public function getPasswordVal()
    {
        return $this->readOneof(10);
    }

    /**
     * <code>string password_val = 10;</code>
     */
    public function setPasswordVal($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(10, $var);

        return $this;
    }

    /**
     * <code>uint64 uid_val = 11;</code>
     */
    public function getUidVal()
    {
        return $this->readOneof(11);
    }

    /**
     * <code>uint64 uid_val = 11;</code>
     */
    public function setUidVal($var)
    {
        GPBUtil::checkUint64($var);
        $this->writeOneof(11, $var);

        return $this;
    }

    public function getVal()
    {
        return $this->whichOneof("val");
    }

}

