<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

namespace Protos;

/**
 * Protobuf enum <code>protos.DirectedEdge.Op</code>
 */
class DirectedEdge_Op
{
    /**
     * <code>SET = 0;</code>
     */
    const SET = 0;
    /**
     * <code>DEL = 1;</code>
     */
    const DEL = 1;
}

