<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>protos.DirectedEdge</code>
 */
class DirectedEdge extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Subject or source node / UID.
     * </pre>
     *
     * <code>fixed64 entity = 1;</code>
     */
    private $entity = 0;
    /**
     * <pre>
     * Attribute or predicate. Labels the edge.
     * </pre>
     *
     * <code>string attr = 2;</code>
     */
    private $attr = '';
    /**
     * <pre>
     * Edge points to a value.
     * </pre>
     *
     * <code>bytes value = 3;</code>
     */
    private $value = '';
    /**
     * <pre>
     * The type of the value
     * </pre>
     *
     * <code>uint32 value_type = 4;</code>
     */
    private $value_type = 0;
    /**
     * <pre>
     * Object or destination node / UID.
     * </pre>
     *
     * <code>fixed64 value_id = 5;</code>
     */
    private $value_id = 0;
    /**
     * <code>string label = 6;</code>
     */
    private $label = '';
    /**
     * <code>string lang = 7;</code>
     */
    private $lang = '';
    /**
     * <code>.protos.DirectedEdge.Op op = 8;</code>
     */
    private $op = 0;
    /**
     * <code>repeated .protos.Facet facets = 9;</code>
     */
    private $facets;

    public function __construct() {
        \GPBMetadata\Task::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Subject or source node / UID.
     * </pre>
     *
     * <code>fixed64 entity = 1;</code>
     */
    public function getEntity()
    {
        return $this->entity;
    }

    /**
     * <pre>
     * Subject or source node / UID.
     * </pre>
     *
     * <code>fixed64 entity = 1;</code>
     */
    public function setEntity($var)
    {
        GPBUtil::checkUint64($var);
        $this->entity = $var;

        return $this;
    }

    /**
     * <pre>
     * Attribute or predicate. Labels the edge.
     * </pre>
     *
     * <code>string attr = 2;</code>
     */
    public function getAttr()
    {
        return $this->attr;
    }

    /**
     * <pre>
     * Attribute or predicate. Labels the edge.
     * </pre>
     *
     * <code>string attr = 2;</code>
     */
    public function setAttr($var)
    {
        GPBUtil::checkString($var, True);
        $this->attr = $var;

        return $this;
    }

    /**
     * <pre>
     * Edge points to a value.
     * </pre>
     *
     * <code>bytes value = 3;</code>
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * <pre>
     * Edge points to a value.
     * </pre>
     *
     * <code>bytes value = 3;</code>
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->value = $var;

        return $this;
    }

    /**
     * <pre>
     * The type of the value
     * </pre>
     *
     * <code>uint32 value_type = 4;</code>
     */
    public function getValueType()
    {
        return $this->value_type;
    }

    /**
     * <pre>
     * The type of the value
     * </pre>
     *
     * <code>uint32 value_type = 4;</code>
     */
    public function setValueType($var)
    {
        GPBUtil::checkUint32($var);
        $this->value_type = $var;

        return $this;
    }

    /**
     * <pre>
     * Object or destination node / UID.
     * </pre>
     *
     * <code>fixed64 value_id = 5;</code>
     */
    public function getValueId()
    {
        return $this->value_id;
    }

    /**
     * <pre>
     * Object or destination node / UID.
     * </pre>
     *
     * <code>fixed64 value_id = 5;</code>
     */
    public function setValueId($var)
    {
        GPBUtil::checkUint64($var);
        $this->value_id = $var;

        return $this;
    }

    /**
     * <code>string label = 6;</code>
     */
    public function getLabel()
    {
        return $this->label;
    }

    /**
     * <code>string label = 6;</code>
     */
    public function setLabel($var)
    {
        GPBUtil::checkString($var, True);
        $this->label = $var;

        return $this;
    }

    /**
     * <code>string lang = 7;</code>
     */
    public function getLang()
    {
        return $this->lang;
    }

    /**
     * <code>string lang = 7;</code>
     */
    public function setLang($var)
    {
        GPBUtil::checkString($var, True);
        $this->lang = $var;

        return $this;
    }

    /**
     * <code>.protos.DirectedEdge.Op op = 8;</code>
     */
    public function getOp()
    {
        return $this->op;
    }

    /**
     * <code>.protos.DirectedEdge.Op op = 8;</code>
     */
    public function setOp($var)
    {
        GPBUtil::checkEnum($var, \Protos\DirectedEdge_Op::class);
        $this->op = $var;

        return $this;
    }

    /**
     * <code>repeated .protos.Facet facets = 9;</code>
     */
    public function getFacets()
    {
        return $this->facets;
    }

    /**
     * <code>repeated .protos.Facet facets = 9;</code>
     */
    public function setFacets(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protos\Facet::class);
        $this->facets = $arr;

        return $this;
    }

}

