<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>protos.GroupKeys</code>
 */
class GroupKeys extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>uint32 group_id = 1;</code>
     */
    private $group_id = 0;
    /**
     * <code>repeated .protos.KC keys = 2;</code>
     */
    private $keys;

    public function __construct() {
        \GPBMetadata\Task::initOnce();
        parent::__construct();
    }

    /**
     * <code>uint32 group_id = 1;</code>
     */
    public function getGroupId()
    {
        return $this->group_id;
    }

    /**
     * <code>uint32 group_id = 1;</code>
     */
    public function setGroupId($var)
    {
        GPBUtil::checkUint32($var);
        $this->group_id = $var;

        return $this;
    }

    /**
     * <code>repeated .protos.KC keys = 2;</code>
     */
    public function getKeys()
    {
        return $this->keys;
    }

    /**
     * <code>repeated .protos.KC keys = 2;</code>
     */
    public function setKeys(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protos\KC::class);
        $this->keys = $arr;

        return $this;
    }

}

