<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>protos.KC</code>
 */
class KC extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>bytes key = 1;</code>
     */
    private $key = '';
    /**
     * <code>bytes checksum = 2;</code>
     */
    private $checksum = '';

    public function __construct() {
        \GPBMetadata\Task::initOnce();
        parent::__construct();
    }

    /**
     * <code>bytes key = 1;</code>
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * <code>bytes key = 1;</code>
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->key = $var;

        return $this;
    }

    /**
     * <code>bytes checksum = 2;</code>
     */
    public function getChecksum()
    {
        return $this->checksum;
    }

    /**
     * <code>bytes checksum = 2;</code>
     */
    public function setChecksum($var)
    {
        GPBUtil::checkString($var, False);
        $this->checksum = $var;

        return $this;
    }

}

