<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * MembershipUpdate is used to pack together the current membership state of all the nodes
 * in the caller server; and the membership updates recorded by the callee server since
 * the provided lastUpdate.
 * </pre>
 *
 * Protobuf type <code>protos.MembershipUpdate</code>
 */
class MembershipUpdate extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .protos.Membership members = 1;</code>
     */
    private $members;
    /**
     * <code>uint64 last_update = 2;</code>
     */
    private $last_update = 0;
    /**
     * <code>bool redirect = 3;</code>
     */
    private $redirect = false;
    /**
     * <code>string redirect_addr = 4;</code>
     */
    private $redirect_addr = '';

    public function __construct() {
        \GPBMetadata\Task::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .protos.Membership members = 1;</code>
     */
    public function getMembers()
    {
        return $this->members;
    }

    /**
     * <code>repeated .protos.Membership members = 1;</code>
     */
    public function setMembers(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protos\Membership::class);
        $this->members = $arr;

        return $this;
    }

    /**
     * <code>uint64 last_update = 2;</code>
     */
    public function getLastUpdate()
    {
        return $this->last_update;
    }

    /**
     * <code>uint64 last_update = 2;</code>
     */
    public function setLastUpdate($var)
    {
        GPBUtil::checkUint64($var);
        $this->last_update = $var;

        return $this;
    }

    /**
     * <code>bool redirect = 3;</code>
     */
    public function getRedirect()
    {
        return $this->redirect;
    }

    /**
     * <code>bool redirect = 3;</code>
     */
    public function setRedirect($var)
    {
        GPBUtil::checkBool($var);
        $this->redirect = $var;

        return $this;
    }

    /**
     * <code>string redirect_addr = 4;</code>
     */
    public function getRedirectAddr()
    {
        return $this->redirect_addr;
    }

    /**
     * <code>string redirect_addr = 4;</code>
     */
    public function setRedirectAddr($var)
    {
        GPBUtil::checkString($var, True);
        $this->redirect_addr = $var;

        return $this;
    }

}

