<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>protos.Proposal</code>
 */
class Proposal extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>uint32 id = 1;</code>
     */
    private $id = 0;
    /**
     * <code>.protos.Mutations mutations = 2;</code>
     */
    private $mutations = null;
    /**
     * <code>.protos.Membership membership = 3;</code>
     */
    private $membership = null;
    /**
     * <code>.protos.RebuildIndexMessage rebuild_index = 4;</code>
     */
    private $rebuild_index = null;

    public function __construct() {
        \GPBMetadata\Task::initOnce();
        parent::__construct();
    }

    /**
     * <code>uint32 id = 1;</code>
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * <code>uint32 id = 1;</code>
     */
    public function setId($var)
    {
        GPBUtil::checkUint32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * <code>.protos.Mutations mutations = 2;</code>
     */
    public function getMutations()
    {
        return $this->mutations;
    }

    /**
     * <code>.protos.Mutations mutations = 2;</code>
     */
    public function setMutations(&$var)
    {
        GPBUtil::checkMessage($var, \Protos\Mutations::class);
        $this->mutations = $var;

        return $this;
    }

    /**
     * <code>.protos.Membership membership = 3;</code>
     */
    public function getMembership()
    {
        return $this->membership;
    }

    /**
     * <code>.protos.Membership membership = 3;</code>
     */
    public function setMembership(&$var)
    {
        GPBUtil::checkMessage($var, \Protos\Membership::class);
        $this->membership = $var;

        return $this;
    }

    /**
     * <code>.protos.RebuildIndexMessage rebuild_index = 4;</code>
     */
    public function getRebuildIndex()
    {
        return $this->rebuild_index;
    }

    /**
     * <code>.protos.RebuildIndexMessage rebuild_index = 4;</code>
     */
    public function setRebuildIndex(&$var)
    {
        GPBUtil::checkMessage($var, \Protos\RebuildIndexMessage::class);
        $this->rebuild_index = $var;

        return $this;
    }

}

