<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>protos.RebuildIndexMessage</code>
 */
class RebuildIndexMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>uint32 group_id = 1;</code>
     */
    private $group_id = 0;
    /**
     * <pre>
     * For simplicity, just do one attribute per request.
     * </pre>
     *
     * <code>string attr = 2;</code>
     */
    private $attr = '';

    public function __construct() {
        \GPBMetadata\Task::initOnce();
        parent::__construct();
    }

    /**
     * <code>uint32 group_id = 1;</code>
     */
    public function getGroupId()
    {
        return $this->group_id;
    }

    /**
     * <code>uint32 group_id = 1;</code>
     */
    public function setGroupId($var)
    {
        GPBUtil::checkUint32($var);
        $this->group_id = $var;

        return $this;
    }

    /**
     * <pre>
     * For simplicity, just do one attribute per request.
     * </pre>
     *
     * <code>string attr = 2;</code>
     */
    public function getAttr()
    {
        return $this->attr;
    }

    /**
     * <pre>
     * For simplicity, just do one attribute per request.
     * </pre>
     *
     * <code>string attr = 2;</code>
     */
    public function setAttr($var)
    {
        GPBUtil::checkString($var, True);
        $this->attr = $var;

        return $this;
    }

}

