<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>protos.SortResult</code>
 */
class SortResult extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .protos.List uid_matrix = 1;</code>
     */
    private $uid_matrix;

    public function __construct() {
        \GPBMetadata\Task::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .protos.List uid_matrix = 1;</code>
     */
    public function getUidMatrix()
    {
        return $this->uid_matrix;
    }

    /**
     * <code>repeated .protos.List uid_matrix = 1;</code>
     */
    public function setUidMatrix(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protos\Lists::class);
        $this->uid_matrix = $arr;

        return $this;
    }

}

