<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>protos.SortMessage</code>
 */
class SortMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string attr = 1;</code>
     */
    private $attr = '';
    /**
     * <code>repeated string langs = 2;</code>
     */
    private $langs;
    /**
     * <code>repeated .protos.List uid_matrix = 3;</code>
     */
    private $uid_matrix;
    /**
     * <pre>
     * Return this many elements.
     * </pre>
     *
     * <code>int32 count = 4;</code>
     */
    private $count = 0;
    /**
     * <pre>
     * Skip this many elements.
     * </pre>
     *
     * <code>int32 offset = 5;</code>
     */
    private $offset = 0;
    /**
     * <code>bool desc = 6;</code>
     */
    private $desc = false;

    public function __construct() {
        \GPBMetadata\Task::initOnce();
        parent::__construct();
    }

    /**
     * <code>string attr = 1;</code>
     */
    public function getAttr()
    {
        return $this->attr;
    }

    /**
     * <code>string attr = 1;</code>
     */
    public function setAttr($var)
    {
        GPBUtil::checkString($var, True);
        $this->attr = $var;

        return $this;
    }

    /**
     * <code>repeated string langs = 2;</code>
     */
    public function getLangs()
    {
        return $this->langs;
    }

    /**
     * <code>repeated string langs = 2;</code>
     */
    public function setLangs(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->langs = $arr;

        return $this;
    }

    /**
     * <code>repeated .protos.List uid_matrix = 3;</code>
     */
    public function getUidMatrix()
    {
        return $this->uid_matrix;
    }

    /**
     * <code>repeated .protos.List uid_matrix = 3;</code>
     */
    public function setUidMatrix(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protos\Lists::class);
        $this->uid_matrix = $arr;

        return $this;
    }

    /**
     * <pre>
     * Return this many elements.
     * </pre>
     *
     * <code>int32 count = 4;</code>
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * <pre>
     * Return this many elements.
     * </pre>
     *
     * <code>int32 count = 4;</code>
     */
    public function setCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->count = $var;

        return $this;
    }

    /**
     * <pre>
     * Skip this many elements.
     * </pre>
     *
     * <code>int32 offset = 5;</code>
     */
    public function getOffset()
    {
        return $this->offset;
    }

    /**
     * <pre>
     * Skip this many elements.
     * </pre>
     *
     * <code>int32 offset = 5;</code>
     */
    public function setOffset($var)
    {
        GPBUtil::checkInt32($var);
        $this->offset = $var;

        return $this;
    }

    /**
     * <code>bool desc = 6;</code>
     */
    public function getDesc()
    {
        return $this->desc;
    }

    /**
     * <code>bool desc = 6;</code>
     */
    public function setDesc($var)
    {
        GPBUtil::checkBool($var);
        $this->desc = $var;

        return $this;
    }

}

