<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: types.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>protos.Posting</code>
 */
class Posting extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>fixed64 uid = 1;</code>
     */
    private $uid = 0;
    /**
     * <code>bytes value = 2;</code>
     */
    private $value = '';
    /**
     * <code>.protos.Posting.ValType val_type = 3;</code>
     */
    private $val_type = 0;
    /**
     * <code>.protos.Posting.PostingType posting_type = 4;</code>
     */
    private $posting_type = 0;
    /**
     * <pre>
     * for VALUE_LANG: Language, for VALUE_TIMESERIES: timestamp, etc..
     * </pre>
     *
     * <code>bytes metadata = 5;</code>
     */
    private $metadata = '';
    /**
     * <code>string label = 6;</code>
     */
    private $label = '';
    /**
     * <pre>
     * More inclination towards smaller values.
     * </pre>
     *
     * <code>uint64 commit = 7;</code>
     */
    private $commit = 0;
    /**
     * <code>repeated .protos.Facet facets = 8;</code>
     */
    private $facets;
    /**
     * <pre>
     * TODO: op is only used temporarily. See if we can remove it from here.
     * </pre>
     *
     * <code>uint32 op = 12;</code>
     */
    private $op = 0;

    public function __construct() {
        \GPBMetadata\Types::initOnce();
        parent::__construct();
    }

    /**
     * <code>fixed64 uid = 1;</code>
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * <code>fixed64 uid = 1;</code>
     */
    public function setUid($var)
    {
        GPBUtil::checkUint64($var);
        $this->uid = $var;

        return $this;
    }

    /**
     * <code>bytes value = 2;</code>
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * <code>bytes value = 2;</code>
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->value = $var;

        return $this;
    }

    /**
     * <code>.protos.Posting.ValType val_type = 3;</code>
     */
    public function getValType()
    {
        return $this->val_type;
    }

    /**
     * <code>.protos.Posting.ValType val_type = 3;</code>
     */
    public function setValType($var)
    {
        GPBUtil::checkEnum($var, \Protos\Posting_ValType::class);
        $this->val_type = $var;

        return $this;
    }

    /**
     * <code>.protos.Posting.PostingType posting_type = 4;</code>
     */
    public function getPostingType()
    {
        return $this->posting_type;
    }

    /**
     * <code>.protos.Posting.PostingType posting_type = 4;</code>
     */
    public function setPostingType($var)
    {
        GPBUtil::checkEnum($var, \Protos\Posting_PostingType::class);
        $this->posting_type = $var;

        return $this;
    }

    /**
     * <pre>
     * for VALUE_LANG: Language, for VALUE_TIMESERIES: timestamp, etc..
     * </pre>
     *
     * <code>bytes metadata = 5;</code>
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * <pre>
     * for VALUE_LANG: Language, for VALUE_TIMESERIES: timestamp, etc..
     * </pre>
     *
     * <code>bytes metadata = 5;</code>
     */
    public function setMetadata($var)
    {
        GPBUtil::checkString($var, False);
        $this->metadata = $var;

        return $this;
    }

    /**
     * <code>string label = 6;</code>
     */
    public function getLabel()
    {
        return $this->label;
    }

    /**
     * <code>string label = 6;</code>
     */
    public function setLabel($var)
    {
        GPBUtil::checkString($var, True);
        $this->label = $var;

        return $this;
    }

    /**
     * <pre>
     * More inclination towards smaller values.
     * </pre>
     *
     * <code>uint64 commit = 7;</code>
     */
    public function getCommit()
    {
        return $this->commit;
    }

    /**
     * <pre>
     * More inclination towards smaller values.
     * </pre>
     *
     * <code>uint64 commit = 7;</code>
     */
    public function setCommit($var)
    {
        GPBUtil::checkUint64($var);
        $this->commit = $var;

        return $this;
    }

    /**
     * <code>repeated .protos.Facet facets = 8;</code>
     */
    public function getFacets()
    {
        return $this->facets;
    }

    /**
     * <code>repeated .protos.Facet facets = 8;</code>
     */
    public function setFacets(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protos\Facet::class);
        $this->facets = $arr;

        return $this;
    }

    /**
     * <pre>
     * TODO: op is only used temporarily. See if we can remove it from here.
     * </pre>
     *
     * <code>uint32 op = 12;</code>
     */
    public function getOp()
    {
        return $this->op;
    }

    /**
     * <pre>
     * TODO: op is only used temporarily. See if we can remove it from here.
     * </pre>
     *
     * <code>uint32 op = 12;</code>
     */
    public function setOp($var)
    {
        GPBUtil::checkUint32($var);
        $this->op = $var;

        return $this;
    }

}

