<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: types.proto

namespace Protos;

/**
 * Protobuf enum <code>protos.Posting.PostingType</code>
 */
class Posting_PostingType
{
    /**
     * <pre>
     * UID
     * </pre>
     *
     * <code>REF = 0;</code>
     */
    const REF = 0;
    /**
     * <pre>
     * simple, plain value
     * </pre>
     *
     * <code>VALUE = 1;</code>
     */
    const VALUE = 1;
    /**
     * <pre>
     * value with specified language
     * </pre>
     *
     * <code>VALUE_LANG = 2;</code>
     */
    const VALUE_LANG = 2;
}

