<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: facets.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>protos.FacetsList</code>
 */
class FacetsList extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .protos.Facets facets_list = 1;</code>
     */
    private $facets_list;

    public function __construct() {
        \GPBMetadata\Facets::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .protos.Facets facets_list = 1;</code>
     */
    public function getFacetsList()
    {
        return $this->facets_list;
    }

    /**
     * <code>repeated .protos.Facets facets_list = 1;</code>
     */
    public function setFacetsList(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protos\Facets::class);
        $this->facets_list = $arr;

        return $this;
    }

}

