<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: facets.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>protos.Facet</code>
 */
class Facet extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string key = 1;</code>
     */
    private $key = '';
    /**
     * <code>bytes value = 2;</code>
     */
    private $value = '';
    /**
     * <code>.protos.Facet.ValType val_type = 3;</code>
     */
    private $val_type = 0;
    /**
     * <pre>
     * tokens of value.
     * </pre>
     *
     * <code>repeated string tokens = 4;</code>
     */
    private $tokens;
    /**
     * <pre>
     * Only used by the Go client, so that we can parse and tokenize facets
     * on the server.
     * </pre>
     *
     * <code>string val = 5;</code>
     */
    private $val = '';

    public function __construct() {
        \GPBMetadata\Facets::initOnce();
        parent::__construct();
    }

    /**
     * <code>string key = 1;</code>
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * <code>string key = 1;</code>
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

    /**
     * <code>bytes value = 2;</code>
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * <code>bytes value = 2;</code>
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->value = $var;

        return $this;
    }

    /**
     * <code>.protos.Facet.ValType val_type = 3;</code>
     */
    public function getValType()
    {
        return $this->val_type;
    }

    /**
     * <code>.protos.Facet.ValType val_type = 3;</code>
     */
    public function setValType($var)
    {
        GPBUtil::checkEnum($var, \Protos\Facet_ValType::class);
        $this->val_type = $var;

        return $this;
    }

    /**
     * <pre>
     * tokens of value.
     * </pre>
     *
     * <code>repeated string tokens = 4;</code>
     */
    public function getTokens()
    {
        return $this->tokens;
    }

    /**
     * <pre>
     * tokens of value.
     * </pre>
     *
     * <code>repeated string tokens = 4;</code>
     */
    public function setTokens(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->tokens = $arr;

        return $this;
    }

    /**
     * <pre>
     * Only used by the Go client, so that we can parse and tokenize facets
     * on the server.
     * </pre>
     *
     * <code>string val = 5;</code>
     */
    public function getVal()
    {
        return $this->val;
    }

    /**
     * <pre>
     * Only used by the Go client, so that we can parse and tokenize facets
     * on the server.
     * </pre>
     *
     * <code>string val = 5;</code>
     */
    public function setVal($var)
    {
        GPBUtil::checkString($var, True);
        $this->val = $var;

        return $this;
    }

}

