<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: facets.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Op and Children are internal nodes and Func on leaves.
 * </pre>
 *
 * Protobuf type <code>protos.FilterTree</code>
 */
class FilterTree extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string op = 1;</code>
     */
    private $op = '';
    /**
     * <code>repeated .protos.FilterTree children = 2;</code>
     */
    private $children;
    /**
     * <code>.protos.Function func = 3;</code>
     */
    private $func = null;

    public function __construct() {
        \GPBMetadata\Facets::initOnce();
        parent::__construct();
    }

    /**
     * <code>string op = 1;</code>
     */
    public function getOp()
    {
        return $this->op;
    }

    /**
     * <code>string op = 1;</code>
     */
    public function setOp($var)
    {
        GPBUtil::checkString($var, True);
        $this->op = $var;

        return $this;
    }

    /**
     * <code>repeated .protos.FilterTree children = 2;</code>
     */
    public function getChildren()
    {
        return $this->children;
    }

    /**
     * <code>repeated .protos.FilterTree children = 2;</code>
     */
    public function setChildren(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protos\FilterTree::class);
        $this->children = $arr;

        return $this;
    }

    /**
     * <code>.protos.Function func = 3;</code>
     */
    public function getFunc()
    {
        return $this->func;
    }

    /**
     * <code>.protos.Function func = 3;</code>
     */
    public function setFunc(&$var)
    {
        GPBUtil::checkMessage($var, \Protos\Functions::class);
        $this->func = $var;

        return $this;
    }

}

