<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: facets.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>protos.Function</code>
 */
class Functions extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * Name of the function : eq, le
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * <pre>
     * Facet key over which to run the function.
     * </pre>
     *
     * <code>string key = 2;</code>
     */
    private $key = '';
    /**
     * <pre>
     * Arguments of the function.
     * </pre>
     *
     * <code>repeated string args = 3;</code>
     */
    private $args;

    public function __construct() {
        \GPBMetadata\Facets::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * Name of the function : eq, le
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * <pre>
     * Name of the function : eq, le
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * <pre>
     * Facet key over which to run the function.
     * </pre>
     *
     * <code>string key = 2;</code>
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * <pre>
     * Facet key over which to run the function.
     * </pre>
     *
     * <code>string key = 2;</code>
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

    /**
     * <pre>
     * Arguments of the function.
     * </pre>
     *
     * <code>repeated string args = 3;</code>
     */
    public function getArgs()
    {
        return $this->args;
    }

    /**
     * <pre>
     * Arguments of the function.
     * </pre>
     *
     * <code>repeated string args = 3;</code>
     */
    public function setArgs(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->args = $arr;

        return $this;
    }

}

