<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use GPBMetadata\Task;

/**
 * Protobuf type <code>protos.Assigned</code>
 */
class Assigned extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>map&lt;string, string&gt; uids = 1;</code>
     */
    private $uids;
    /**
     * <code>.protos.TxnContext context = 2;</code>
     */
    private $context = null;
    /**
     * <code>string error = 3;</code>
     */
    private $error = '';

    public function __construct() {
        Task::initOnce();
        parent::__construct();
    }

    /**
     * <code>map&lt;string, string&gt; uids = 1;</code>
     */
    public function getUids()
    {
        return $this->uids;
    }

    /**
     * <code>map&lt;string, string&gt; uids = 1;</code>
     */
    public function setUids(&$var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->uids = $arr;

        return $this;
    }

    /**
     * <code>.protos.TxnContext context = 2;</code>
     */
    public function getContext()
    {
        return $this->context;
    }

    /**
     * <code>.protos.TxnContext context = 2;</code>
     */
    public function setContext(&$var)
    {
        GPBUtil::checkMessage($var, TxnContext::class);
        $this->context = $var;

        return $this;
    }

    /**
     * <code>string error = 3;</code>
     */
    public function getError()
    {
        return $this->error;
    }

    /**
     * <code>string error = 3;</code>
     */
    public function setError($var)
    {
        GPBUtil::checkString($var, True);
        $this->error = $var;

        return $this;
    }

}

