<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use GPBMetadata\Task;

/**
 * Protobuf type <code>protos.Check</code>
 */
class Check extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        Task::initOnce();
        parent::__construct();
    }

}

