<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use GPBMetadata\Task;

/**
 * Protobuf type <code>protos.ConnectionState</code>
 */
class ConnectionState extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.protos.Member member = 1;</code>
     */
    private $member = null;
    /**
     * <code>.protos.MembershipState state = 2;</code>
     */
    private $state = null;

    public function __construct() {
        Task::initOnce();
        parent::__construct();
    }

    /**
     * <code>.protos.Member member = 1;</code>
     */
    public function getMember()
    {
        return $this->member;
    }

    /**
     * <code>.protos.Member member = 1;</code>
     */
    public function setMember(&$var)
    {
        GPBUtil::checkMessage($var, Member::class);
        $this->member = $var;

        return $this;
    }

    /**
     * <code>.protos.MembershipState state = 2;</code>
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * <code>.protos.MembershipState state = 2;</code>
     */
    public function setState(&$var)
    {
        GPBUtil::checkMessage($var, MembershipState::class);
        $this->state = $var;

        return $this;
    }

}

