<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

namespace Protos;

/**
 * Protobuf enum <code>protos.ExportPayload.Status</code>
 */
class ExportPayload_Status
{
    /**
     * <code>NONE = 0;</code>
     */
    const NONE = 0;
    /**
     * <code>SUCCESS = 1;</code>
     */
    const SUCCESS = 1;
    /**
     * <code>DUPLICATE = 2;</code>
     */
    const DUPLICATE = 2;
    /**
     * <code>FAILED = 3;</code>
     */
    const FAILED = 3;
}

