<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use GPBMetadata\Task;

/**
 * Protobuf type <code>protos.Facets</code>
 */
class Facets extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .protos.Facet facets = 1;</code>
     */
    private $facets;

    public function __construct() {
        Task::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .protos.Facet facets = 1;</code>
     */
    public function getFacets()
    {
        return $this->facets;
    }

    /**
     * <code>repeated .protos.Facet facets = 1;</code>
     */
    public function setFacets(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, Facet::class);
        $this->facets = $arr;

        return $this;
    }

}

