<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

namespace Protos;

/**
 * Protobuf enum <code>protos.Facet.ValType</code>
 */
class Facet_ValType
{
    /**
     * <code>STRING = 0;</code>
     */
    const STRING = 0;
    /**
     * <code>INT = 1;</code>
     */
    const INT = 1;
    /**
     * <code>FLOAT = 2;</code>
     */
    const FLOAT = 2;
    /**
     * <code>BOOL = 3;</code>
     */
    const BOOL = 3;
    /**
     * <code>DATETIME = 4;</code>
     */
    const DATETIME = 4;
}

