<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use GPBMetadata\Task;

/**
 * Protobuf type <code>protos.KC</code>
 */
class KC extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>bytes key = 1;</code>
     */
    private $key = '';
    /**
     * <code>uint64 timestamp = 2;</code>
     */
    private $timestamp = 0;

    public function __construct() {
        Task::initOnce();
        parent::__construct();
    }

    /**
     * <code>bytes key = 1;</code>
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * <code>bytes key = 1;</code>
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->key = $var;

        return $this;
    }

    /**
     * <code>uint64 timestamp = 2;</code>
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * <code>uint64 timestamp = 2;</code>
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->timestamp = $var;

        return $this;
    }

}

