<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use GPBMetadata\Task;

/**
 * Protobuf type <code>protos.KV</code>
 */
class KV extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>bytes key = 1;</code>
     */
    private $key = '';
    /**
     * <code>bytes val = 2;</code>
     */
    private $val = '';
    /**
     * <code>bytes userMeta = 3;</code>
     */
    private $userMeta = '';
    /**
     * <code>uint64 version = 4;</code>
     */
    private $version = 0;

    public function __construct() {
        Task::initOnce();
        parent::__construct();
    }

    /**
     * <code>bytes key = 1;</code>
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * <code>bytes key = 1;</code>
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->key = $var;

        return $this;
    }

    /**
     * <code>bytes val = 2;</code>
     */
    public function getVal()
    {
        return $this->val;
    }

    /**
     * <code>bytes val = 2;</code>
     */
    public function setVal($var)
    {
        GPBUtil::checkString($var, False);
        $this->val = $var;

        return $this;
    }

    /**
     * <code>bytes userMeta = 3;</code>
     */
    public function getUserMeta()
    {
        return $this->userMeta;
    }

    /**
     * <code>bytes userMeta = 3;</code>
     */
    public function setUserMeta($var)
    {
        GPBUtil::checkString($var, False);
        $this->userMeta = $var;

        return $this;
    }

    /**
     * <code>uint64 version = 4;</code>
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * <code>uint64 version = 4;</code>
     */
    public function setVersion($var)
    {
        GPBUtil::checkUint64($var);
        $this->version = $var;

        return $this;
    }

}

