<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use GPBMetadata\Task;

/**
 * Protobuf type <code>protos.LinRead</code>
 */
class LinRead extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>map&lt;uint32, uint64&gt; ids = 1;</code>
     */
    private $ids;

    public function __construct() {
        Task::initOnce();
        parent::__construct();
    }

    /**
     * <code>map&lt;uint32, uint64&gt; ids = 1;</code>
     */
    public function getIds()
    {
        return $this->ids;
    }

    /**
     * <code>map&lt;uint32, uint64&gt; ids = 1;</code>
     */
    public function setIds(&$var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::UINT32, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->ids = $arr;

        return $this;
    }

}

