<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use GPBMetadata\Task;

/**
 * <pre>
 * Bulk loader proto.
 * </pre>
 *
 * Protobuf type <code>protos.MapEntry</code>
 */
class MapEntry extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>bytes key = 1;</code>
     */
    private $key = '';
    /**
     * <pre>
     * Only one should be set.
     * </pre>
     *
     * <code>fixed64 uid = 2;</code>
     */
    private $uid = 0;
    /**
     * <code>.protos.Posting posting = 3;</code>
     */
    private $posting = null;

    public function __construct() {
        Task::initOnce();
        parent::__construct();
    }

    /**
     * <code>bytes key = 1;</code>
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * <code>bytes key = 1;</code>
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->key = $var;

        return $this;
    }

    /**
     * <pre>
     * Only one should be set.
     * </pre>
     *
     * <code>fixed64 uid = 2;</code>
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * <pre>
     * Only one should be set.
     * </pre>
     *
     * <code>fixed64 uid = 2;</code>
     */
    public function setUid($var)
    {
        GPBUtil::checkUint64($var);
        $this->uid = $var;

        return $this;
    }

    /**
     * <code>.protos.Posting posting = 3;</code>
     */
    public function getPosting()
    {
        return $this->posting;
    }

    /**
     * <code>.protos.Posting posting = 3;</code>
     */
    public function setPosting(&$var)
    {
        GPBUtil::checkMessage($var, Posting::class);
        $this->posting = $var;

        return $this;
    }

}

