<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use GPBMetadata\Task;

/**
 * Protobuf type <code>protos.MovePredicatePayload</code>
 */
class MovePredicatePayload extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string predicate = 1;</code>
     */
    private $predicate = '';
    /**
     * <code>uint32 source_group_id = 2;</code>
     */
    private $source_group_id = 0;
    /**
     * <code>uint32 dest_group_id = 3;</code>
     */
    private $dest_group_id = 0;
    /**
     * <code>.protos.MembershipState state = 4;</code>
     */
    private $state = null;

    public function __construct() {
        Task::initOnce();
        parent::__construct();
    }

    /**
     * <code>string predicate = 1;</code>
     */
    public function getPredicate()
    {
        return $this->predicate;
    }

    /**
     * <code>string predicate = 1;</code>
     */
    public function setPredicate($var)
    {
        GPBUtil::checkString($var, True);
        $this->predicate = $var;

        return $this;
    }

    /**
     * <code>uint32 source_group_id = 2;</code>
     */
    public function getSourceGroupId()
    {
        return $this->source_group_id;
    }

    /**
     * <code>uint32 source_group_id = 2;</code>
     */
    public function setSourceGroupId($var)
    {
        GPBUtil::checkUint32($var);
        $this->source_group_id = $var;

        return $this;
    }

    /**
     * <code>uint32 dest_group_id = 3;</code>
     */
    public function getDestGroupId()
    {
        return $this->dest_group_id;
    }

    /**
     * <code>uint32 dest_group_id = 3;</code>
     */
    public function setDestGroupId($var)
    {
        GPBUtil::checkUint32($var);
        $this->dest_group_id = $var;

        return $this;
    }

    /**
     * <code>.protos.MembershipState state = 4;</code>
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * <code>.protos.MembershipState state = 4;</code>
     */
    public function setState(&$var)
    {
        GPBUtil::checkMessage($var, MembershipState::class);
        $this->state = $var;

        return $this;
    }

}

