<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use GPBMetadata\Task;

/**
 * Protobuf type <code>protos.Mutations</code>
 */
class Mutations extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>uint32 group_id = 1;</code>
     */
    private $group_id = 0;
    /**
     * <code>uint64 start_ts = 2;</code>
     */
    private $start_ts = 0;
    /**
     * <code>repeated .protos.DirectedEdge edges = 3;</code>
     */
    private $edges;
    /**
     * <code>repeated .protos.SchemaUpdate schema = 4;</code>
     */
    private $schema;
    /**
     * <code>bool DropAll = 5;</code>
     */
    private $DropAll = false;

    public function __construct() {
        Task::initOnce();
        parent::__construct();
    }

    /**
     * <code>uint32 group_id = 1;</code>
     */
    public function getGroupId()
    {
        return $this->group_id;
    }

    /**
     * <code>uint32 group_id = 1;</code>
     */
    public function setGroupId($var)
    {
        GPBUtil::checkUint32($var);
        $this->group_id = $var;

        return $this;
    }

    /**
     * <code>uint64 start_ts = 2;</code>
     */
    public function getStartTs()
    {
        return $this->start_ts;
    }

    /**
     * <code>uint64 start_ts = 2;</code>
     */
    public function setStartTs($var)
    {
        GPBUtil::checkUint64($var);
        $this->start_ts = $var;

        return $this;
    }

    /**
     * <code>repeated .protos.DirectedEdge edges = 3;</code>
     */
    public function getEdges()
    {
        return $this->edges;
    }

    /**
     * <code>repeated .protos.DirectedEdge edges = 3;</code>
     */
    public function setEdges(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, DirectedEdge::class);
        $this->edges = $arr;

        return $this;
    }

    /**
     * <code>repeated .protos.SchemaUpdate schema = 4;</code>
     */
    public function getSchema()
    {
        return $this->schema;
    }

    /**
     * <code>repeated .protos.SchemaUpdate schema = 4;</code>
     */
    public function setSchema(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, SchemaUpdate::class);
        $this->schema = $arr;

        return $this;
    }

    /**
     * <code>bool DropAll = 5;</code>
     */
    public function getDropAll()
    {
        return $this->DropAll;
    }

    /**
     * <code>bool DropAll = 5;</code>
     */
    public function setDropAll($var)
    {
        GPBUtil::checkBool($var);
        $this->DropAll = $var;

        return $this;
    }

}

