<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use GPBMetadata\Task;

/**
 * Protobuf type <code>protos.NQuad</code>
 */
class NQuad extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string subject = 1;</code>
     */
    private $subject = '';
    /**
     * <code>string predicate = 2;</code>
     */
    private $predicate = '';
    /**
     * <code>string object_id = 3;</code>
     */
    private $object_id = '';
    /**
     * <code>.protos.Value object_value = 4;</code>
     */
    private $object_value = null;
    /**
     * <code>string label = 5;</code>
     */
    private $label = '';
    /**
     * <code>string lang = 6;</code>
     */
    private $lang = '';
    /**
     * <code>repeated .protos.Facet facets = 7;</code>
     */
    private $facets;

    public function __construct() {
        Task::initOnce();
        parent::__construct();
    }

    /**
     * <code>string subject = 1;</code>
     */
    public function getSubject()
    {
        return $this->subject;
    }

    /**
     * <code>string subject = 1;</code>
     */
    public function setSubject($var)
    {
        GPBUtil::checkString($var, True);
        $this->subject = $var;

        return $this;
    }

    /**
     * <code>string predicate = 2;</code>
     */
    public function getPredicate()
    {
        return $this->predicate;
    }

    /**
     * <code>string predicate = 2;</code>
     */
    public function setPredicate($var)
    {
        GPBUtil::checkString($var, True);
        $this->predicate = $var;

        return $this;
    }

    /**
     * <code>string object_id = 3;</code>
     */
    public function getObjectId()
    {
        return $this->object_id;
    }

    /**
     * <code>string object_id = 3;</code>
     */
    public function setObjectId($var)
    {
        GPBUtil::checkString($var, True);
        $this->object_id = $var;

        return $this;
    }

    /**
     * <code>.protos.Value object_value = 4;</code>
     */
    public function getObjectValue()
    {
        return $this->object_value;
    }

    /**
     * <code>.protos.Value object_value = 4;</code>
     */
    public function setObjectValue(&$var)
    {
        GPBUtil::checkMessage($var, Value::class);
        $this->object_value = $var;

        return $this;
    }

    /**
     * <code>string label = 5;</code>
     */
    public function getLabel()
    {
        return $this->label;
    }

    /**
     * <code>string label = 5;</code>
     */
    public function setLabel($var)
    {
        GPBUtil::checkString($var, True);
        $this->label = $var;

        return $this;
    }

    /**
     * <code>string lang = 6;</code>
     */
    public function getLang()
    {
        return $this->lang;
    }

    /**
     * <code>string lang = 6;</code>
     */
    public function setLang($var)
    {
        GPBUtil::checkString($var, True);
        $this->lang = $var;

        return $this;
    }

    /**
     * <code>repeated .protos.Facet facets = 7;</code>
     */
    public function getFacets()
    {
        return $this->facets;
    }

    /**
     * <code>repeated .protos.Facet facets = 7;</code>
     */
    public function setFacets(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, Facet::class);
        $this->facets = $arr;

        return $this;
    }

}

