<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use GPBMetadata\Task;

/**
 * Protobuf type <code>protos.Operation</code>
 */
class Operation extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string schema = 1;</code>
     */
    private $schema = '';
    /**
     * <code>string drop_attr = 2;</code>
     */
    private $drop_attr = '';
    /**
     * <code>bool drop_all = 3;</code>
     */
    private $drop_all = false;
    /**
     * <code>uint64 startTs = 4;</code>
     */
    private $startTs = 0;

    public function __construct() {
        Task::initOnce();
        parent::__construct();
    }

    /**
     * <code>string schema = 1;</code>
     */
    public function getSchema()
    {
        return $this->schema;
    }

    /**
     * <code>string schema = 1;</code>
     */
    public function setSchema($var)
    {
        GPBUtil::checkString($var, True);
        $this->schema = $var;

        return $this;
    }

    /**
     * <code>string drop_attr = 2;</code>
     */
    public function getDropAttr()
    {
        return $this->drop_attr;
    }

    /**
     * <code>string drop_attr = 2;</code>
     */
    public function setDropAttr($var)
    {
        GPBUtil::checkString($var, True);
        $this->drop_attr = $var;

        return $this;
    }

    /**
     * <code>bool drop_all = 3;</code>
     */
    public function getDropAll()
    {
        return $this->drop_all;
    }

    /**
     * <code>bool drop_all = 3;</code>
     */
    public function setDropAll($var)
    {
        GPBUtil::checkBool($var);
        $this->drop_all = $var;

        return $this;
    }

    /**
     * <code>uint64 startTs = 4;</code>
     */
    public function getStartTs()
    {
        return $this->startTs;
    }

    /**
     * <code>uint64 startTs = 4;</code>
     */
    public function setStartTs($var)
    {
        GPBUtil::checkUint64($var);
        $this->startTs = $var;

        return $this;
    }

}

