<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use GPBMetadata\Task;

/**
 * Protobuf type <code>protos.PBList</code>
 */
class PBList extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated fixed64 uids = 1;</code>
     */
    private $uids;

    public function __construct() {
        Task::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated fixed64 uids = 1;</code>
     */
    public function getUids()
    {
        return $this->uids;
    }

    /**
     * <code>repeated fixed64 uids = 1;</code>
     */
    public function setUids(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FIXED64);
        $this->uids = $arr;

        return $this;
    }

}

