<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

namespace Protos;

/**
 * Protobuf enum <code>protos.Posting.ValType</code>
 */
class Posting_ValType
{
    /**
     * <code>DEFAULT = 0;</code>
     */
    const DEFAULT = 0;
    /**
     * <code>BINARY = 1;</code>
     */
    const BINARY = 1;
    /**
     * <pre>
     * We treat it as int64.
     * </pre>
     *
     * <code>INT = 2;</code>
     */
    const INT = 2;
    /**
     * <code>FLOAT = 3;</code>
     */
    const FLOAT = 3;
    /**
     * <code>BOOL = 4;</code>
     */
    const BOOL = 4;
    /**
     * <code>DATETIME = 5;</code>
     */
    const DATETIME = 5;
    /**
     * <code>GEO = 6;</code>
     */
    const GEO = 6;
    /**
     * <code>UID = 7;</code>
     */
    const UID = 7;
    /**
     * <code>PASSWORD = 8;</code>
     */
    const PASSWORD = 8;
    /**
     * <code>STRING = 9;</code>
     */
    const STRING = 9;
}

