<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use GPBMetadata\Task;

/**
 * Protobuf type <code>protos.RaftContext</code>
 */
class RaftContext extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>fixed64 id = 1;</code>
     */
    private $id = 0;
    /**
     * <code>uint32 group = 2;</code>
     */
    private $group = 0;
    /**
     * <code>string addr = 3;</code>
     */
    private $addr = '';

    public function __construct() {
        Task::initOnce();
        parent::__construct();
    }

    /**
     * <code>fixed64 id = 1;</code>
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * <code>fixed64 id = 1;</code>
     */
    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * <code>uint32 group = 2;</code>
     */
    public function getGroup()
    {
        return $this->group;
    }

    /**
     * <code>uint32 group = 2;</code>
     */
    public function setGroup($var)
    {
        GPBUtil::checkUint32($var);
        $this->group = $var;

        return $this;
    }

    /**
     * <code>string addr = 3;</code>
     */
    public function getAddr()
    {
        return $this->addr;
    }

    /**
     * <code>string addr = 3;</code>
     */
    public function setAddr($var)
    {
        GPBUtil::checkString($var, True);
        $this->addr = $var;

        return $this;
    }

}

