<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use GPBMetadata\Task;

/**
 * Protobuf type <code>protos.SortMessage</code>
 */
class SortMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .protos.Order order = 1;</code>
     */
    private $order;
    /**
     * <code>repeated .protos.PBList uid_matrix = 2;</code>
     */
    private $uid_matrix;
    /**
     * <pre>
     * Return this many elements.
     * </pre>
     *
     * <code>int32 count = 3;</code>
     */
    private $count = 0;
    /**
     * <pre>
     * Skip this many elements.
     * </pre>
     *
     * <code>int32 offset = 4;</code>
     */
    private $offset = 0;
    /**
     * <code>uint64 read_ts = 13;</code>
     */
    private $read_ts = 0;
    /**
     * <code>.protos.LinRead lin_read = 14;</code>
     */
    private $lin_read = null;

    public function __construct() {
        Task::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .protos.Order order = 1;</code>
     */
    public function getOrder()
    {
        return $this->order;
    }

    /**
     * <code>repeated .protos.Order order = 1;</code>
     */
    public function setOrder(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, Order::class);
        $this->order = $arr;

        return $this;
    }

    /**
     * <code>repeated .protos.PBList uid_matrix = 2;</code>
     */
    public function getUidMatrix()
    {
        return $this->uid_matrix;
    }

    /**
     * <code>repeated .protos.PBList uid_matrix = 2;</code>
     */
    public function setUidMatrix(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, PBList::class);
        $this->uid_matrix = $arr;

        return $this;
    }

    /**
     * <pre>
     * Return this many elements.
     * </pre>
     *
     * <code>int32 count = 3;</code>
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * <pre>
     * Return this many elements.
     * </pre>
     *
     * <code>int32 count = 3;</code>
     */
    public function setCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->count = $var;

        return $this;
    }

    /**
     * <pre>
     * Skip this many elements.
     * </pre>
     *
     * <code>int32 offset = 4;</code>
     */
    public function getOffset()
    {
        return $this->offset;
    }

    /**
     * <pre>
     * Skip this many elements.
     * </pre>
     *
     * <code>int32 offset = 4;</code>
     */
    public function setOffset($var)
    {
        GPBUtil::checkInt32($var);
        $this->offset = $var;

        return $this;
    }

    /**
     * <code>uint64 read_ts = 13;</code>
     */
    public function getReadTs()
    {
        return $this->read_ts;
    }

    /**
     * <code>uint64 read_ts = 13;</code>
     */
    public function setReadTs($var)
    {
        GPBUtil::checkUint64($var);
        $this->read_ts = $var;

        return $this;
    }

    /**
     * <code>.protos.LinRead lin_read = 14;</code>
     */
    public function getLinRead()
    {
        return $this->lin_read;
    }

    /**
     * <code>.protos.LinRead lin_read = 14;</code>
     */
    public function setLinRead(&$var)
    {
        GPBUtil::checkMessage($var, LinRead::class);
        $this->lin_read = $var;

        return $this;
    }

}

