<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use GPBMetadata\Task;

/**
 * Protobuf type <code>protos.SortResult</code>
 */
class SortResult extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .protos.PBList uid_matrix = 1;</code>
     */
    private $uid_matrix;
    /**
     * <code>.protos.LinRead lin_read = 14;</code>
     */
    private $lin_read = null;

    public function __construct() {
        Task::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .protos.PBList uid_matrix = 1;</code>
     */
    public function getUidMatrix()
    {
        return $this->uid_matrix;
    }

    /**
     * <code>repeated .protos.PBList uid_matrix = 1;</code>
     */
    public function setUidMatrix(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, PBList::class);
        $this->uid_matrix = $arr;

        return $this;
    }

    /**
     * <code>.protos.LinRead lin_read = 14;</code>
     */
    public function getLinRead()
    {
        return $this->lin_read;
    }

    /**
     * <code>.protos.LinRead lin_read = 14;</code>
     */
    public function setLinRead(&$var)
    {
        GPBUtil::checkMessage($var, LinRead::class);
        $this->lin_read = $var;

        return $this;
    }

}

