<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use GPBMetadata\Task;

/**
 * Protobuf type <code>protos.ValueList</code>
 */
class ValueList extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .protos.TaskValue values = 1;</code>
     */
    private $values;

    public function __construct() {
        Task::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .protos.TaskValue values = 1;</code>
     */
    public function getValues()
    {
        return $this->values;
    }

    /**
     * <code>repeated .protos.TaskValue values = 1;</code>
     */
    public function setValues(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, TaskValue::class);
        $this->values = $arr;

        return $this;
    }

}

