<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use GPBMetadata\Task;

/**
 * Protobuf type <code>protos.ZeroProposal</code>
 */
class ZeroProposal extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>uint32 id = 1;</code>
     */
    private $id = 0;
    /**
     * <code>.protos.Member member = 2;</code>
     */
    private $member = null;
    /**
     * <code>.protos.Tablet tablet = 3;</code>
     */
    private $tablet = null;
    /**
     * <code>uint64 maxLeaseId = 4;</code>
     */
    private $maxLeaseId = 0;
    /**
     * <code>uint64 maxTxnTs = 5;</code>
     */
    private $maxTxnTs = 0;
    /**
     * <code>uint64 maxRaftId = 6;</code>
     */
    private $maxRaftId = 0;
    /**
     * <code>.protos.TxnContext txn = 7;</code>
     */
    private $txn = null;

    public function __construct() {
        Task::initOnce();
        parent::__construct();
    }

    /**
     * <code>uint32 id = 1;</code>
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * <code>uint32 id = 1;</code>
     */
    public function setId($var)
    {
        GPBUtil::checkUint32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * <code>.protos.Member member = 2;</code>
     */
    public function getMember()
    {
        return $this->member;
    }

    /**
     * <code>.protos.Member member = 2;</code>
     */
    public function setMember(&$var)
    {
        GPBUtil::checkMessage($var, Member::class);
        $this->member = $var;

        return $this;
    }

    /**
     * <code>.protos.Tablet tablet = 3;</code>
     */
    public function getTablet()
    {
        return $this->tablet;
    }

    /**
     * <code>.protos.Tablet tablet = 3;</code>
     */
    public function setTablet(&$var)
    {
        GPBUtil::checkMessage($var, Tablet::class);
        $this->tablet = $var;

        return $this;
    }

    /**
     * <code>uint64 maxLeaseId = 4;</code>
     */
    public function getMaxLeaseId()
    {
        return $this->maxLeaseId;
    }

    /**
     * <code>uint64 maxLeaseId = 4;</code>
     */
    public function setMaxLeaseId($var)
    {
        GPBUtil::checkUint64($var);
        $this->maxLeaseId = $var;

        return $this;
    }

    /**
     * <code>uint64 maxTxnTs = 5;</code>
     */
    public function getMaxTxnTs()
    {
        return $this->maxTxnTs;
    }

    /**
     * <code>uint64 maxTxnTs = 5;</code>
     */
    public function setMaxTxnTs($var)
    {
        GPBUtil::checkUint64($var);
        $this->maxTxnTs = $var;

        return $this;
    }

    /**
     * <code>uint64 maxRaftId = 6;</code>
     */
    public function getMaxRaftId()
    {
        return $this->maxRaftId;
    }

    /**
     * <code>uint64 maxRaftId = 6;</code>
     */
    public function setMaxRaftId($var)
    {
        GPBUtil::checkUint64($var);
        $this->maxRaftId = $var;

        return $this;
    }

    /**
     * <code>.protos.TxnContext txn = 7;</code>
     */
    public function getTxn()
    {
        return $this->txn;
    }

    /**
     * <code>.protos.TxnContext txn = 7;</code>
     */
    public function setTxn(&$var)
    {
        GPBUtil::checkMessage($var, TxnContext::class);
        $this->txn = $var;

        return $this;
    }

}

